# theme
theme: jekyll-theme-minimal
title: Stephania Contreras Castillo
owner:
  linkedin: "stephania-contreras-castillo"
# build
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
# specific stuff
github:
  is_project_page: false
  is_user_page: false
show_downloads: false

