# theme
theme: jekyll-theme-minimal
title: Stephania Contreras Castillo
blank_title: true
description: ""
# build
markdown: kramdown
# specific stuff
github:
  is_project_page: false
  is_user_page: false
show_downloads: false
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
