# theme
theme: jekyll-theme-minimal
title: Stephania Contreras Castillo
# build
markdown: kramdown
# specific stuff
github:
  is_project_page: false
  is_user_page: false
show_downloads: false
  social_links:
        - { platform: linkedin,       user_url: "https://www.linkedin.com/in/stephania-contreras-castillo" }
