# theme
theme: jekyll-theme-minimal
title: Stephania Contreras Castillo
# build
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
# specific stuff
github:
  is_project_page: false
  is_user_page: false
show_downloads: false
social_links:
        - { platform: linkedin,       user_url: "https://www.linkedin.com/in/stephania-contreras-castillo" }
header_pages:
- about.md